# Chiave univoca del progetto e nome visualizzato su SonarQube
sonar.projectKey=BugBoard-Back-End
sonar.projectName=BugBoard Back-End
sonar.projectVersion=1.0

# Dove si trova il codice sorgente (il punto indica la cartella corrente)
sonar.sources=.

# Escludi dall'analisi le cartelle che non contengono codice sorgente tuo
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/.next/**, **/.git/**, **/coverage/**, **/*.mp4, **/*.json# Codifica dei file
sonar.sourceEncoding=UTF-8